"""Type stubs for the Rust extension module ``scdata._scdata``.

These mirror the pyclasses registered by ``rust/scdata/src/pybind.rs``.  The
simple config dataclasses (``DataBankConfig``, ``IoConfig``, ...) are exposed
verbatim; ``_DataBank`` and ``_PrefetchCells`` are private and wrapped by
:mod:`scdata.databank` into the public ``ScDataBank`` / prefetch iterator.
"""

from __future__ import annotations

from typing import Any, Iterable, Iterator, Optional

from numpy.typing import NDArray

__version__: str


def kernel_name() -> str: ...
def kernel_version() -> str: ...


class DataBankError(RuntimeError):
    """Raised when a Rust-side DataBank operation fails."""


# ---------------------------------------------------------------------------
# DatasetId — simple value object, exposed directly
# ---------------------------------------------------------------------------


class _DatasetId:
    """Opaque ``(slot, generation)`` handle returned by ``register_*``."""

    def __init__(self, slot: int, generation: int) -> None: ...
    @property
    def slot(self) -> int: ...
    @property
    def generation(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...


# ---------------------------------------------------------------------------
# MissingGenePolicy — simple enum, exposed directly
# ---------------------------------------------------------------------------


class _MissingGenePolicy:
    """Policy for gene names absent from the dataset (``ZERO`` / ``ERROR``)."""

    ZERO: MissingGenePolicy
    ERROR: MissingGenePolicy
    def __init__(self, policy: str) -> None: ...
    def __repr__(self) -> str: ...


# ---------------------------------------------------------------------------
# Config dataclasses — exposed directly, attribute get/set
# ---------------------------------------------------------------------------


class _BaseIoConfig:
    def __init__(self) -> None: ...
    @property
    def max_in_flight(self) -> int: ...
    @max_in_flight.setter
    def max_in_flight(self, value: int) -> None: ...
    @property
    def priority_levels(self) -> int: ...
    @priority_levels.setter
    def priority_levels(self, value: int) -> None: ...
    @property
    def queue_shards(self) -> int: ...
    @queue_shards.setter
    def queue_shards(self, value: int) -> None: ...
    @property
    def assume_non_overlapping_reads(self) -> bool: ...
    @assume_non_overlapping_reads.setter
    def assume_non_overlapping_reads(self, value: bool) -> None: ...
    def __repr__(self) -> str: ...


class _UringConfig:
    def __init__(self) -> None: ...
    @property
    def base(self) -> BaseIoConfig: ...
    @base.setter
    def base(self, value: BaseIoConfig) -> None: ...
    @property
    def entries(self) -> int: ...
    @entries.setter
    def entries(self, value: int) -> None: ...
    @property
    def drivers(self) -> int: ...
    @drivers.setter
    def drivers(self, value: int) -> None: ...
    @property
    def iowq_bounded_workers(self) -> int: ...
    @iowq_bounded_workers.setter
    def iowq_bounded_workers(self, value: int) -> None: ...
    @property
    def iowq_unbounded_workers(self) -> int: ...
    @iowq_unbounded_workers.setter
    def iowq_unbounded_workers(self, value: int) -> None: ...
    @property
    def registered_files(self) -> int: ...
    @registered_files.setter
    def registered_files(self, value: int) -> None: ...


class _ThreadedConfig:
    def __init__(self) -> None: ...
    @property
    def base(self) -> BaseIoConfig: ...
    @base.setter
    def base(self, value: BaseIoConfig) -> None: ...
    @property
    def num_workers(self) -> int: ...
    @num_workers.setter
    def num_workers(self, value: int) -> None: ...
    @property
    def cpus(self) -> Optional[list[int]]: ...
    @cpus.setter
    def cpus(self, value: Optional[list[int]]) -> None: ...


class _IoConfig:
    """IO backend selection (``IoConfig.uring(...)`` / ``.threaded(...)``)."""

    def __init__(self) -> None: ...
    @staticmethod
    def uring(config: Optional[UringConfig] = ...) -> IoConfig: ...
    @staticmethod
    def threaded(config: Optional[ThreadedConfig] = ...) -> IoConfig: ...
    @property
    def kind(self) -> str: ...
    def __repr__(self) -> str: ...


class _DecodePoolConfig:
    def __init__(self) -> None: ...
    @property
    def num_workers(self) -> int: ...
    @num_workers.setter
    def num_workers(self, value: int) -> None: ...
    @property
    def queue_capacity(self) -> int: ...
    @queue_capacity.setter
    def queue_capacity(self, value: int) -> None: ...
    @property
    def cpus(self) -> Optional[list[int]]: ...
    @cpus.setter
    def cpus(self, value: Optional[list[int]]) -> None: ...


class _AccessCpuConfig:
    def __init__(self) -> None: ...
    @property
    def num_workers(self) -> int: ...
    @num_workers.setter
    def num_workers(self, value: int) -> None: ...
    @property
    def queue_capacity(self) -> int: ...
    @queue_capacity.setter
    def queue_capacity(self, value: int) -> None: ...
    @property
    def cpus(self) -> Optional[list[int]]: ...
    @cpus.setter
    def cpus(self, value: Optional[list[int]]) -> None: ...


class _AccessConfig:
    def __init__(self) -> None: ...
    @property
    def queue_capacity(self) -> int: ...
    @queue_capacity.setter
    def queue_capacity(self, value: int) -> None: ...
    @property
    def scheduler_shards(self) -> int: ...
    @scheduler_shards.setter
    def scheduler_shards(self, value: int) -> None: ...
    @property
    def cache_capacity_bytes(self) -> int: ...
    @cache_capacity_bytes.setter
    def cache_capacity_bytes(self, value: int) -> None: ...
    @property
    def memory_budget_bytes(self) -> int: ...
    @memory_budget_bytes.setter
    def memory_budget_bytes(self, value: int) -> None: ...
    @property
    def default_io_priority(self) -> int: ...
    @default_io_priority.setter
    def default_io_priority(self, value: int) -> None: ...
    @property
    def keep_decoded(self) -> bool: ...
    @keep_decoded.setter
    def keep_decoded(self, value: bool) -> None: ...
    @property
    def cpu(self) -> AccessCpuConfig: ...
    @cpu.setter
    def cpu(self, value: AccessCpuConfig) -> None: ...


class _FillConfig:
    def __init__(self) -> None: ...
    @property
    def parallel(self) -> bool: ...
    @parallel.setter
    def parallel(self, value: bool) -> None: ...
    @property
    def num_workers(self) -> int: ...
    @num_workers.setter
    def num_workers(self, value: int) -> None: ...
    @property
    def queue_capacity(self) -> int: ...
    @queue_capacity.setter
    def queue_capacity(self, value: int) -> None: ...
    @property
    def min_parallel_rows(self) -> int: ...
    @min_parallel_rows.setter
    def min_parallel_rows(self, value: int) -> None: ...
    @property
    def min_parallel_bytes(self) -> int: ...
    @min_parallel_bytes.setter
    def min_parallel_bytes(self, value: int) -> None: ...
    @property
    def cpus(self) -> Optional[list[int]]: ...
    @cpus.setter
    def cpus(self, value: Optional[list[int]]) -> None: ...


class _DataBankConfig:
    def __init__(self) -> None: ...
    @property
    def io_config(self) -> IoConfig: ...
    @io_config.setter
    def io_config(self, value: IoConfig) -> None: ...
    @property
    def decode_config(self) -> DecodePoolConfig: ...
    @decode_config.setter
    def decode_config(self, value: DecodePoolConfig) -> None: ...
    @property
    def access_config(self) -> AccessConfig: ...
    @access_config.setter
    def access_config(self, value: AccessConfig) -> None: ...
    @property
    def fill_config(self) -> FillConfig: ...
    @fill_config.setter
    def fill_config(self, value: FillConfig) -> None: ...


class _ScheduledAccessConfig:
    def __init__(self) -> None: ...
    @property
    def prefetch_step(self) -> int: ...
    @prefetch_step.setter
    def prefetch_step(self, value: int) -> None: ...
    @property
    def decode_ahead_steps(self) -> int: ...
    @decode_ahead_steps.setter
    def decode_ahead_steps(self, value: int) -> None: ...
    @property
    def ready_ahead_steps(self) -> int: ...
    @ready_ahead_steps.setter
    def ready_ahead_steps(self, value: int) -> None: ...


class _ScheduledPrefetchConfig:
    def __init__(self) -> None: ...
    @property
    def prefetch_step(self) -> int: ...
    @prefetch_step.setter
    def prefetch_step(self, value: int) -> None: ...
    @property
    def access(self) -> ScheduledAccessConfig: ...
    @access.setter
    def access(self, value: ScheduledAccessConfig) -> None: ...


# ---------------------------------------------------------------------------
# _DataBank — private, wrapped by scdata.databank.ScDataBank
# ---------------------------------------------------------------------------


class _DataBank:
    def __init__(self, config: Optional[DataBankConfig] = None) -> None: ...
    def register_dense(self, ds: Any, store_path: str) -> DatasetId: ...
    def register_sparse_csr(self, ds: Any, store_path: str) -> DatasetId: ...
    def unregister(self, id: DatasetId) -> None: ...
    def dataset_genes(self, id: DatasetId) -> list[str]: ...
    def dataset_num_cells(self, id: DatasetId) -> int: ...
    def dataset_num_genes(self, id: DatasetId) -> int: ...
    def dataset_dtype(self, id: DatasetId) -> Any: ...
    def access_cells(
        self,
        id: DatasetId,
        cells: list[int],
        dtype: Optional[Any] = None,
    ) -> NDArray[Any]: ...
    def access_cells_by_gene_names(
        self,
        id: DatasetId,
        cells: list[int],
        gene_names: list[str],
        missing: Optional[MissingGenePolicy] = None,
        dtype: Optional[Any] = None,
    ) -> NDArray[Any]: ...
    def prefetch_cells(
        self,
        id: DatasetId,
        batches: Iterable[list[int]],
        config: Optional[ScheduledPrefetchConfig] = None,
    ) -> _PrefetchCells: ...
    def prefetch_cells_by_gene_names(
        self,
        id: DatasetId,
        batches: Iterable[list[int]],
        gene_names: list[str],
        missing: Optional[MissingGenePolicy] = None,
        config: Optional[ScheduledPrefetchConfig] = None,
    ) -> _PrefetchCells: ...
    def __repr__(self) -> str: ...


# ---------------------------------------------------------------------------
# _PrefetchCells — private iterator yielding (cells, ndarray, num_genes)
# tuples; wrapped by scdata.databank into PrefetchedBatch objects.
# ---------------------------------------------------------------------------


class _PrefetchCells:
    def __iter__(self) -> Iterator[tuple[NDArray[Any], NDArray[Any], int]]: ...
    def __next__(self) -> tuple[NDArray[Any], NDArray[Any], int]: ...
