"""Type stubs for the Rust extension module ``scdata._scdata``.

These mirror the pyclasses registered by ``rust/scdata/src/pybind/``.  The
types here are intentionally the current breaking interface only; old
``*Meta`` compatibility pyclasses are not present in the Rust binding anymore.
"""

from __future__ import annotations

from typing import Any, Iterable, Literal, TypeAlias

import numpy as np
from numpy.typing import NDArray

from scdata.data._dataset import DenseDataset, DType, SparseDataset

__version__: str

ProfileSnapshot: TypeAlias = dict[str, Any]

def kernel_name() -> str: ...
def kernel_version() -> str: ...
def _zip_stored_offsets(path: str, header_offsets: list[int]) -> list[int]: ...
def _decode_index_payload(
    payload: bytes,
    offsets: Iterable[int] | NDArray[np.uint64],
    lengths: Iterable[int] | NDArray[np.uint64],
    dtype: DType | str,
    codec: Any,
    count: int,
) -> NDArray[np.uint64]: ...
def _decode_index_chunks(
    chunks: Iterable[bytes],
    dtype: DType | str,
    codec: Any,
    count: int,
) -> NDArray[np.uint64]: ...

class DataBankError(RuntimeError):
    """Raised when a Rust-side DataBank operation fails."""

class _DatasetId:
    def __init__(self, slot: int, generation: int) -> None: ...
    @property
    def slot(self) -> int: ...
    @property
    def generation(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

class _MissingGenePolicy:
    ZERO: _MissingGenePolicy
    ERROR: _MissingGenePolicy
    def __init__(self, policy: Literal["zero", "error"] | str) -> None: ...
    def __repr__(self) -> str: ...

class _BaseIoConfig:
    def __init__(self) -> None: ...
    @property
    def max_in_flight(self) -> int: ...
    @max_in_flight.setter
    def max_in_flight(self, value: int) -> None: ...
    @property
    def priority_levels(self) -> int: ...
    @priority_levels.setter
    def priority_levels(self, value: int) -> None: ...
    @property
    def queue_shards(self) -> int: ...
    @queue_shards.setter
    def queue_shards(self, value: int) -> None: ...
    @property
    def assume_non_overlapping_reads(self) -> bool: ...
    @assume_non_overlapping_reads.setter
    def assume_non_overlapping_reads(self, value: bool) -> None: ...
    def validate(self) -> None: ...

class _UringConfig:
    def __init__(self) -> None: ...
    @property
    def base(self) -> _BaseIoConfig: ...
    @base.setter
    def base(self, value: _BaseIoConfig) -> None: ...
    @property
    def entries(self) -> int: ...
    @entries.setter
    def entries(self, value: int) -> None: ...
    @property
    def drivers(self) -> int: ...
    @drivers.setter
    def drivers(self, value: int) -> None: ...
    @property
    def iowq_bounded_workers(self) -> int: ...
    @iowq_bounded_workers.setter
    def iowq_bounded_workers(self, value: int) -> None: ...
    @property
    def iowq_unbounded_workers(self) -> int: ...
    @iowq_unbounded_workers.setter
    def iowq_unbounded_workers(self, value: int) -> None: ...
    @property
    def registered_files(self) -> int: ...
    @registered_files.setter
    def registered_files(self, value: int) -> None: ...
    def validate(self) -> None: ...

class _ThreadedConfig:
    def __init__(self) -> None: ...
    @property
    def base(self) -> _BaseIoConfig: ...
    @base.setter
    def base(self, value: _BaseIoConfig) -> None: ...
    @property
    def num_workers(self) -> int: ...
    @num_workers.setter
    def num_workers(self, value: int) -> None: ...
    @property
    def cpus(self) -> list[int] | None: ...
    @cpus.setter
    def cpus(self, value: list[int] | None) -> None: ...
    def validate(self) -> None: ...

class _IoConfig:
    def __init__(self) -> None: ...
    @staticmethod
    def uring(config: _UringConfig | None = None) -> _IoConfig: ...
    @staticmethod
    def threaded(config: _ThreadedConfig | None = None) -> _IoConfig: ...
    @property
    def kind(self) -> Literal["uring", "threaded"]: ...
    @property
    def base(self) -> _BaseIoConfig: ...
    def uring_config(self) -> _UringConfig | None: ...
    def threaded_config(self) -> _ThreadedConfig | None: ...
    def validate(self) -> None: ...

class _DecodePoolConfig:
    def __init__(self) -> None: ...
    @property
    def num_workers(self) -> int: ...
    @num_workers.setter
    def num_workers(self, value: int) -> None: ...
    @property
    def queue_capacity(self) -> int: ...
    @queue_capacity.setter
    def queue_capacity(self, value: int) -> None: ...
    @property
    def cpus(self) -> list[int] | None: ...
    @cpus.setter
    def cpus(self, value: list[int] | None) -> None: ...
    def validate(self) -> None: ...

class _AccessCpuConfig:
    def __init__(self) -> None: ...
    @property
    def num_workers(self) -> int: ...
    @num_workers.setter
    def num_workers(self, value: int) -> None: ...
    @property
    def queue_capacity(self) -> int: ...
    @queue_capacity.setter
    def queue_capacity(self, value: int) -> None: ...
    @property
    def cpus(self) -> list[int] | None: ...
    @cpus.setter
    def cpus(self, value: list[int] | None) -> None: ...
    def validate(self) -> None: ...

class _AccessConfig:
    def __init__(self) -> None: ...
    @property
    def queue_capacity(self) -> int: ...
    @queue_capacity.setter
    def queue_capacity(self, value: int) -> None: ...
    @property
    def scheduler_shards(self) -> int: ...
    @scheduler_shards.setter
    def scheduler_shards(self, value: int) -> None: ...
    @property
    def cache_capacity_bytes(self) -> int: ...
    @cache_capacity_bytes.setter
    def cache_capacity_bytes(self, value: int) -> None: ...
    @property
    def memory_budget_bytes(self) -> int: ...
    @memory_budget_bytes.setter
    def memory_budget_bytes(self, value: int) -> None: ...
    @property
    def default_io_priority(self) -> int: ...
    @default_io_priority.setter
    def default_io_priority(self, value: int) -> None: ...
    @property
    def keep_decoded(self) -> bool: ...
    @keep_decoded.setter
    def keep_decoded(self, value: bool) -> None: ...
    @property
    def cpu(self) -> _AccessCpuConfig: ...
    @cpu.setter
    def cpu(self, value: _AccessCpuConfig) -> None: ...
    def validate(self) -> None: ...

class _FillConfig:
    def __init__(self) -> None: ...
    @property
    def parallel(self) -> bool: ...
    @parallel.setter
    def parallel(self, value: bool) -> None: ...
    @property
    def num_workers(self) -> int: ...
    @num_workers.setter
    def num_workers(self, value: int) -> None: ...
    @property
    def queue_capacity(self) -> int: ...
    @queue_capacity.setter
    def queue_capacity(self, value: int) -> None: ...
    @property
    def min_parallel_rows(self) -> int: ...
    @min_parallel_rows.setter
    def min_parallel_rows(self, value: int) -> None: ...
    @property
    def min_parallel_bytes(self) -> int: ...
    @min_parallel_bytes.setter
    def min_parallel_bytes(self, value: int) -> None: ...
    @property
    def cpus(self) -> list[int] | None: ...
    @cpus.setter
    def cpus(self, value: list[int] | None) -> None: ...
    def validate(self) -> None: ...

class _DataBankConfig:
    def __init__(self) -> None: ...
    @property
    def io_config(self) -> _IoConfig: ...
    @io_config.setter
    def io_config(self, value: _IoConfig) -> None: ...
    @property
    def decode_config(self) -> _DecodePoolConfig: ...
    @decode_config.setter
    def decode_config(self, value: _DecodePoolConfig) -> None: ...
    @property
    def access_config(self) -> _AccessConfig: ...
    @access_config.setter
    def access_config(self, value: _AccessConfig) -> None: ...
    @property
    def fill_config(self) -> _FillConfig: ...
    @fill_config.setter
    def fill_config(self, value: _FillConfig) -> None: ...
    def validate(self) -> None: ...

class _ScheduledAccessConfig:
    def __init__(self) -> None: ...
    @property
    def prefetch_step(self) -> int: ...
    @prefetch_step.setter
    def prefetch_step(self, value: int) -> None: ...
    @property
    def decode_ahead_steps(self) -> int: ...
    @decode_ahead_steps.setter
    def decode_ahead_steps(self, value: int) -> None: ...
    @property
    def ready_ahead_steps(self) -> int: ...
    @ready_ahead_steps.setter
    def ready_ahead_steps(self, value: int) -> None: ...
    def validate(self) -> None: ...

class _ScheduledPrefetchConfig:
    def __init__(self) -> None: ...
    @property
    def prefetch_step(self) -> int: ...
    @prefetch_step.setter
    def prefetch_step(self, value: int) -> None: ...
    @property
    def access(self) -> _ScheduledAccessConfig: ...
    @access.setter
    def access(self, value: _ScheduledAccessConfig) -> None: ...
    def validate(self) -> None: ...

class _DataBank:
    def __init__(self, config: _DataBankConfig | None = None) -> None: ...
    def config(self) -> _DataBankConfig: ...
    def profile_snapshot(self) -> ProfileSnapshot: ...
    def profile_snapshot_and_reset(self) -> ProfileSnapshot: ...
    def reset_profile(self) -> None: ...
    def register_dense(self, ds: DenseDataset, store_path: str) -> _DatasetId: ...
    def register_sparse_csr(self, ds: SparseDataset, store_path: str) -> _DatasetId: ...
    def unregister(self, id: _DatasetId) -> None: ...
    def dataset_genes(self, id: _DatasetId) -> list[str]: ...
    def dataset_num_cells(self, id: _DatasetId) -> int: ...
    def dataset_num_genes(self, id: _DatasetId) -> int: ...
    def dataset_dtype(self, id: _DatasetId) -> DType: ...
    def access_cells(
        self,
        id: _DatasetId,
        cells: Iterable[int],
        dtype: DType | str | None = None,
        config: _ScheduledAccessConfig | None = None,
    ) -> NDArray[np.generic]: ...
    def access_cells_array(
        self,
        id: _DatasetId,
        cells: NDArray[np.intp],
        dtype: DType | str | None = None,
        config: _ScheduledAccessConfig | None = None,
    ) -> NDArray[np.generic]: ...
    def access_cells_by_gene_names(
        self,
        id: _DatasetId,
        cells: Iterable[int],
        gene_names: list[str],
        missing: _MissingGenePolicy | None = None,
        dtype: DType | str | None = None,
        config: _ScheduledAccessConfig | None = None,
    ) -> NDArray[np.generic]: ...
    def access_cells_by_gene_names_array(
        self,
        id: _DatasetId,
        cells: NDArray[np.intp],
        gene_names: list[str],
        missing: _MissingGenePolicy | None = None,
        dtype: DType | str | None = None,
        config: _ScheduledAccessConfig | None = None,
    ) -> NDArray[np.generic]: ...
    def prefetch_cells_cache(self, id: _DatasetId, cells: Iterable[int]) -> None: ...
    def prefetch_cells_cache_array(self, id: _DatasetId, cells: NDArray[np.intp]) -> None: ...
    def prefetch_cells(
        self,
        dataset_ids: list[_DatasetId],
        batches: Iterable[Iterable[tuple[int, Iterable[int] | NDArray[np.intp]]]],
        output_dtype: DType | str,
        gene_names: list[str] | None = None,
        missing: _MissingGenePolicy | None = None,
        config: _ScheduledPrefetchConfig | None = None,
    ) -> _PrefetchCells: ...
    def prefetch_cells_raw(
        self,
        id: _DatasetId,
        batches: Iterable[Iterable[int] | NDArray[np.intp]],
        config: _ScheduledPrefetchConfig | None = None,
    ) -> _PrefetchCells: ...
    def prefetch_cells_by_gene_names_raw(
        self,
        id: _DatasetId,
        batches: Iterable[Iterable[int] | NDArray[np.intp]],
        gene_names: list[str],
        missing: _MissingGenePolicy | None = None,
        config: _ScheduledPrefetchConfig | None = None,
    ) -> _PrefetchCells: ...
    def __repr__(self) -> str: ...

class _PrefetchCells:
    @property
    def prefetch_step(self) -> int: ...
    @property
    def gene_names(self) -> list[str]: ...
    def __iter__(self) -> _PrefetchCells: ...
    def __next__(self) -> tuple[NDArray[np.intp], NDArray[np.generic], int]: ...
