"""Types for the private Rust extension ``sc_load._core``."""

from __future__ import annotations

from os import PathLike
from typing import Any, Literal

import numpy as np
from numpy.typing import NDArray

__version__: str
OUTPUT_DTYPES: tuple[str, ...]
DEFAULT_MAXIMUM_METADATA_SIZE: int
DEFAULT_MAXIMUM_ENCODED_SIZE: int
DEFAULT_MAXIMUM_DECODED_SIZE: int
DEFAULT_MAXIMUM_BLOCK_COUNT: int
DEFAULT_MAX_SHARED_CONTROL_BYTES: int

class CoreError(Exception):
    kind: str

class _Dataset:
    @property
    def kind(self) -> Literal["dense", "csr"]: ...
    @property
    def shape(self) -> tuple[int, int]: ...
    @property
    def n_rows(self) -> int: ...
    @property
    def n_cols(self) -> int: ...
    @property
    def dtype(self) -> Literal["i16", "i32", "u16", "u32", "u64", "f32", "f64"]: ...

class _Plan:
    @property
    def batch_size(self) -> int: ...
    @property
    def batch_count(self) -> int: ...
    @property
    def prefetch_step(self) -> int: ...
    @property
    def n_cols(self) -> int: ...
    @property
    def dtype(self) -> Literal["i16", "i32", "u16", "u32", "f32", "f64"]: ...
    @property
    def row_stride_bytes(self) -> int: ...
    @property
    def is_empty(self) -> bool: ...
    def stats(self) -> dict[str, Any]: ...
    def open(self, config: dict[str, int | str]) -> _Session: ...
    def open_shared(
        self,
        config: dict[str, int | str],
        world_size: int,
        maximum_control_bytes: int | None = None,
    ) -> _SharedServer: ...

class _Session:
    @property
    def closed(self) -> bool: ...
    @property
    def exhausted(self) -> bool: ...
    @property
    def state(self) -> Literal["running", "failed", "cancelled", "finished"]: ...
    def next_batch(self) -> NDArray[Any] | None: ...
    def cancel(self) -> None: ...
    def close(self) -> None: ...
    def stats(self) -> dict[str, Any]: ...

class _SharedServer:
    @property
    def world_size(self) -> int: ...
    @property
    def n_rows(self) -> int: ...
    @property
    def n_cols(self) -> int: ...
    @property
    def batch_size(self) -> int: ...
    @property
    def batch_count(self) -> int: ...
    @property
    def row_stride_bytes(self) -> int: ...
    @property
    def dtype(self) -> Literal["i16", "i32", "u16", "u32", "f32", "f64"]: ...
    @property
    def state(self) -> Literal["running", "failed", "cancelled", "finished"]: ...
    def run(self) -> None: ...
    def cancel(self) -> None: ...
    def duplicate_fd(self) -> int: ...

class _SharedClient:
    @property
    def rank(self) -> int: ...
    @property
    def world_size(self) -> int: ...
    @property
    def n_rows(self) -> int: ...
    @property
    def n_cols(self) -> int: ...
    @property
    def batch_size(self) -> int: ...
    @property
    def batch_count(self) -> int: ...
    @property
    def dtype(self) -> Literal["i16", "i32", "u16", "u32", "f32", "f64"]: ...
    @property
    def closed(self) -> bool: ...
    @property
    def exhausted(self) -> bool: ...
    @property
    def next_logical_batch(self) -> int | None: ...
    def next_batch(self) -> NDArray[Any] | None: ...
    def close(self) -> None: ...

def _plan_config_defaults() -> dict[str, int | float]: ...
def _session_config_defaults() -> dict[str, int | str]: ...
def _attach_shared(fd: int, rank: int) -> _SharedClient: ...
def _open_dataset(
    path: str | PathLike[str],
    *,
    zip_prefix: str | None = None,
    maximum_metadata_size: int,
    maximum_encoded_size: int,
    maximum_decoded_size: int,
    maximum_block_count: int,
) -> _Dataset: ...
def _compile(
    datasets: list[_Dataset],
    source_ids: list[int],
    feature_maps: list[NDArray[np.int64] | None],
    row_source_ids: NDArray[np.uint32] | None,
    row_indices: NDArray[np.uint64],
    output: dict[str, object],
    batch_size: int,
    prefetch_step: int,
    config: dict[str, int | float],
) -> _Plan: ...
