[package]
name = "scdata-python"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Private Python bindings for scdata-toolkit"
publish.workspace = true

[lib]
name = "_core"
crate-type = ["cdylib", "rlib"]
doc = false

[features]
default = []
extension-module = ["pyo3/extension-module"]
profile = ["sc-load/profile"]

[dependencies]
numpy = "0.23"
parking_lot = "0.12"
pyo3 = { version = "0.23.5", features = ["abi3-py312"] }
sc-compress = { path = "../sc-compress" }
sc-load = { path = "../sc-load" }
