use std::fs;
use std::path::PathBuf;

use dyn_blosc::{BloscVersion, Codec, Decoder, Encoder, Shuffle};

const SOURCE_LEN: usize = 32 * 1024 + 2048;
const BLOCK_SIZE: usize = 8192;

fn source() -> Vec<u8> {
    (0..SOURCE_LEN)
        .map(|index| ((index / 4) % 251) as u8)
        .collect()
}

fn configurations() -> impl Iterator<Item = (Codec, Shuffle, bool)> {
    [Codec::BloscLz, Codec::Lz4, Codec::Zlib, Codec::Zstd]
        .into_iter()
        .flat_map(|codec| {
            [Shuffle::None, Shuffle::Bytes, Shuffle::Bits]
                .into_iter()
                .flat_map(move |shuffle| {
                    [false, true]
                        .into_iter()
                        .map(move |split| (codec, shuffle, split))
                })
        })
}

fn fixture_name(prefix: &str, codec: Codec, shuffle: Shuffle, split: bool) -> String {
    format!(
        "{prefix}-{}-{}-{}.blosc",
        match codec {
            Codec::BloscLz => "blosclz",
            Codec::Lz4 => "lz4",
            Codec::Zlib => "zlib",
            Codec::Zstd => "zstd",
        },
        match shuffle {
            Shuffle::None => "none",
            Shuffle::Bytes => "bytes",
            Shuffle::Bits => "bits",
        },
        if split { "split" } else { "unsplit" }
    )
}

/// Run manually with `DYN_BLOSC_INTEROP_DIR` pointing at fixtures generated by
/// the local c-blosc compatibility driver. The test also emits Rust chunks for
/// the driver to decode.
#[test]
#[ignore = "requires local c-blosc fixture generation"]
fn local_cblosc_and_rust_chunks_cross_decode() {
    let directory = PathBuf::from(
        std::env::var_os("DYN_BLOSC_INTEROP_DIR")
            .expect("DYN_BLOSC_INTEROP_DIR must point at generated c-blosc fixtures"),
    );
    let source = source();
    let mut failures = Vec::new();

    for (codec, shuffle, split) in configurations() {
        let c_path = directory.join(fixture_name("c", codec, shuffle, split));
        let c_encoded = fs::read(&c_path)
            .unwrap_or_else(|error| panic!("failed to read {}: {error}", c_path.display()));
        let decoded = Decoder::from_encoded(&c_encoded)
            .and_then(|decoder| decoder.decode(&c_encoded))
            .unwrap_or_else(|error| panic!("failed to decode {}: {error}", c_path.display()));
        if decoded != source {
            let first_mismatch = decoded
                .iter()
                .zip(&source)
                .position(|(actual, expected)| actual != expected)
                .expect("different buffers must contain a mismatching byte");
            failures.push(format!(
                "{} at byte {}: decoded={}, expected={}",
                c_path.display(),
                first_mismatch,
                decoded[first_mismatch],
                source[first_mismatch],
            ));
        }

        let rust_encoded = Encoder::new()
            .version(BloscVersion::Blosc1)
            .codec(codec)
            .shuffle(shuffle)
            .element_size(4)
            .split_blocks(split)
            .block_size(BLOCK_SIZE)
            .encode(&source)
            .unwrap();
        let rust_path = directory.join(fixture_name("rust", codec, shuffle, split));
        fs::write(&rust_path, rust_encoded)
            .unwrap_or_else(|error| panic!("failed to write {}: {error}", rust_path.display()));
    }

    assert!(
        failures.is_empty(),
        "c-blosc decode failures:\n{}",
        failures.join("\n")
    );
}
