from os import PathLike
from typing import Any, Literal

import numpy as np
from numpy.typing import NDArray

class Error(Exception):
    kind: str

class InvalidArgumentError(Error): ...
class InvalidInputError(Error): ...
class InvalidConfigError(Error): ...
class InvalidDatasetError(Error): ...
class InvalidMetaError(Error): ...
class ResourceLimitError(Error): ...
class StalePlanError(Error): ...
class UnsupportedError(Error): ...
class IoError(Error): ...
class JsonError(Error): ...
class CodecError(Error): ...
class ZipError(Error): ...
class DecodeError(Error): ...
class PromotionError(Error): ...
class ConversionError(Error): ...
class CancelledError(Error): ...
class SessionError(Error): ...
class WorkerPanicError(Error): ...
class AllocationError(Error): ...
class InternalError(Error): ...
class NotFoundError(Error): ...
class CorruptDataError(Error): ...
class PathError(Error): ...
class Warning(UserWarning): ...
class PerformanceWarning(Warning): ...
class _Store: ...
class _Dataset: ...
class _Plan: ...
class _Session: ...
class _SharedServer: ...
class _SharedClient: ...

def store_open(
    path: str | PathLike[str],
    *,
    zip_prefix: str | None,
    max_metadata_size: int,
    max_encoded_size: int,
    max_decoded_size: int,
    max_block_count: int,
    num_workers: int,
) -> _Store: ...
def store_meta(store: _Store) -> dict[str, Any]: ...
def store_indptr(store: _Store) -> NDArray[np.uint64] | None: ...
def store_decode_dense_rows(store: _Store, start: int, end: int) -> NDArray[Any]: ...
def store_decode_csr_rows(
    store: _Store,
    start: int,
    end: int,
) -> tuple[NDArray[Any], NDArray[Any], NDArray[np.uint64]]: ...
def store_select(
    store: _Store,
    row_kind: str,
    row_payload: Any,
    col_kind: str,
    col_payload: Any,
    *,
    csr_output: Literal["sparse", "dense"],
) -> Any: ...
def write_dense(
    path: str | PathLike[str],
    values: NDArray[Any],
    *,
    chunk_policy: str,
    chunk_n: int,
    block_policy: str,
    block_n: int,
    num_workers: int,
) -> None: ...
def write_csr(
    path: str | PathLike[str],
    indptr: NDArray[Any],
    indices: NDArray[Any],
    data: NDArray[Any],
    n_rows: int,
    n_cols: int,
    *,
    chunk_policy: str,
    chunk_n: int,
    block_policy: str,
    block_n: int,
    num_workers: int,
) -> None: ...
def matrix_dense_select(
    values: NDArray[Any],
    row_kind: str,
    row_payload: Any,
    col_kind: str,
    col_payload: Any,
    *,
    num_workers: int,
) -> NDArray[Any]: ...
def matrix_csr_select(
    indptr: NDArray[Any],
    indices: NDArray[Any],
    data: NDArray[Any],
    n_rows: int,
    n_cols: int,
    row_kind: str,
    row_payload: Any,
    col_kind: str,
    col_payload: Any,
    *,
    csr_output: Literal["sparse", "dense"],
    num_workers: int,
) -> Any: ...
def matrix_csr_to_dense(
    indptr: NDArray[Any],
    indices: NDArray[Any],
    data: NDArray[Any],
    n_rows: int,
    n_cols: int,
    *,
    num_workers: int,
) -> NDArray[Any]: ...
def dataset_open(
    path: str | PathLike[str],
    *,
    zip_prefix: str | None,
    max_metadata_size: int,
    max_encoded_size: int,
    max_decoded_size: int,
    max_block_count: int,
    num_workers: int,
) -> _Dataset: ...
def dataset_meta(dataset: _Dataset) -> dict[str, Any]: ...
def plan_compile(
    datasets: list[_Dataset],
    source_ids: list[int],
    feature_maps: list[NDArray[np.int64] | None],
    row_source_ids: NDArray[np.uint32] | None,
    row_indices: NDArray[np.uint64],
    output: dict[str, Any],
    batch_size: int,
    prefetch_step: int,
    config: dict[str, Any],
) -> _Plan: ...
def plan_meta(plan: _Plan) -> dict[str, Any]: ...
def plan_stats(plan: _Plan) -> dict[str, Any]: ...
def plan_open(plan: _Plan, config: dict[str, Any]) -> _Session: ...
def plan_open_shared(
    plan: _Plan,
    config: dict[str, Any],
    world_size: int,
    max_control_bytes: int,
) -> _SharedServer: ...
def session_next(session: _Session) -> NDArray[Any] | None: ...
def session_cancel(session: _Session) -> None: ...
def session_close(session: _Session) -> None: ...
def session_meta(session: _Session) -> dict[str, Any]: ...
def session_stats(session: _Session) -> dict[str, Any]: ...
def shared_run(server: _SharedServer) -> None: ...
def shared_cancel(server: _SharedServer) -> None: ...
def shared_server_meta(server: _SharedServer) -> dict[str, Any]: ...
def shared_duplicate_fd(server: _SharedServer) -> int: ...
def shared_attach(descriptor: int, rank: int) -> _SharedClient: ...
def shared_next(client: _SharedClient) -> NDArray[Any] | None: ...
def shared_next_copy(client: _SharedClient) -> NDArray[Any] | None: ...
def shared_read(client: _SharedClient, remaining: int) -> tuple[NDArray[Any], int]: ...
def shared_close(client: _SharedClient) -> None: ...
def shared_client_meta(client: _SharedClient) -> dict[str, Any]: ...
